### ISSUE TITLE
Doesn’t seem to validate Canadian Dexcom Accounts

### ISSUE THREAD

**Issue by CaptainSweatpants** [gagebenne/home-assistant-dexcom#4]
Dexcom accounts created through uam2.dexcom.com (Canada) don’t cross over into Dexcom’s uam1.dexcom.com registration database. The Apple Canadian App Store only distributes their Canadian version which only validates Canadian accounts. Upon making accounts on both urls, the Intergration sets up with the US uam1.dexcom.com account I made, but I get _unknown_ states because my app is logged into the uam2.dexcom.com registration database. The Canadian app will not validate uam1.dexcom.com registrations either here

**Comment by gagebenne** [comment]
This is helpful, thank you! I will add the additional server today and get back to you!

Just so I know when asking questions, how comfortable are you with Python / command line?

**Comment by gagebenne** [comment]
It seems the `share1` and `share2` are in fact identical on the backend. I was able to use both of them for my US Dexcom Share account, receiving the same account ID. I think this may rule out the idea of an additional server outside of the US and EU servers.

Some people have had problems with connecting when their Dexcom passwords are entirely numeric. If you have connection issues in that case, try changing your password to something with a mix of numbers and letters.

**Comment by CaptainSweatpants** [comment]
I did consider my L/P format to potentially be an issue. My username is my email (with an @), and my password starts with an “!” But is letters and numbers after that. I will try and setup a new account without an email as a username,and without the exclamation starting the password, then I’ll get back to you

**Comment by CaptainSweatpants** [comment]
For some reason I can’t set up a new dexcom account at the moment; probably an issue with dexcom. But I did add a “dependent” account to my main one without any special characters in the username or password — this logged into the component fine. So, I’m pretty sure it’s those special characters in my username and/or password that’s causing the login issue. Unfortunately, my dependent account isn’t receiving data at the moment. But this may still be a dexcom issue. Ill give it 24hrs

**Comment by CaptainSweatpants** [comment]
Confirmed. Readings coming in fine now.
