### ISSUE TITLE
What are the trend strings?

### ISSUE THREAD

**Issue by SteveRMann** [gagebenne/home-assistant-dexcom#5]
I am using Node Red to publish CGM data over MQTT to some displays that I have scattered about the house.
The display firmware is expecting a numeric value for the trends, 2 - 6.
I have determined that 3="rising slightly", 4="steady", and 5="falling slightly"
So that I can finish coding the other trends, what is the exact text for "rising fast" and "falling fast"?

**Comment by gagebenne** [comment]
Checkout the [pydexcom module](https://github.com/gagebenne/pydexcom) being used in this integration, should find what you're looking for there.

**Comment by SteveRMann** [comment]
Thanks, that's what I was looking for.
And, my "unavailable" is back.....
What steps do I need to take to uninstall and reinstall the Dexcom component?

**Comment by gagebenne** [comment]
I think if you just delete the component folder, that should do it. A stable release via HA is coming quite soon, so waiting for that is also an option.
